# Generated by Django 4.1.5 on 2023-03-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_exx_cover_alter_exx_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ass',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
