# Generated by Django 4.1.5 on 2023-03-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_ass_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exx',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
