# Generated by Django 4.1.5 on 2023-03-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_exx_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exx',
            name='url',
        ),
    ]
