# Generated by Django 4.1.5 on 2023-04-17 13:20

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_pagevisit_current_time_pagevisit_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
