# Generated by Django 4.1.5 on 2023-04-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_pagevisit_city_pagevisit_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagevisit',
            name='city',
        ),
        migrations.RemoveField(
            model_name='pagevisit',
            name='country',
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
