# Generated by Django 4.1.5 on 2023-04-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_pagevisit_city_remove_pagevisit_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='time_spent_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
